Dodawanie testów selenium
pikol93/PG_BE pull request #72
Opened 2023-11-14 17:31 UTC by michalszulowski

2023-11-21 18:24 UTC, pikol93 approved these changes

2023-11-21 18:24 UTC, pikol93 commented on tests/selenium/presta_runner.py
> +    __GO_TO_ORDER_XPATH = '//*[@id="blockcart-modal"]/div/div/div[2]/div/div[2]/div/div/a'
:)

2023-11-22 09:16 UTC, Sladamos commented on tests/selenium/presta_runner.py
> +    __GO_TO_ORDER_XPATH = '//*[@id="blockcart-modal"]/div/div/div[2]/div/div[2]/div/div/a'
div div divvvvvvvvvvvvvvvvvvv

2023-11-22 21:29 UTC, Sladamos requested changes
Zmien folder na Tests zeby jakiś porzadek był

2023-11-23 18:21 UTC, Sladamos approved these changes

2023-11-23 18:21 UTC, merged